// shared/rule.ts：按方案生成 CLAUDE.md 规则块的默认文字。纯函数，不读写文件。
import { test } from 'node:test';
import assert from 'node:assert/strict';
import type { Preset, PresetAgent } from '../../shared/types.ts';

const { ADVISOR_RULE_TEXT, BUILTIN_AGENT_NAMES, defaultRuleText, DIVISION_HEADING, looksAutoGenerated, ruleOutline, ruleSummary, ruleWhen } = await import('../../shared/rule.ts');
const { BUILTIN_AGENT_TYPES } = await import('../src/config.ts');
const { agentTemplate } = await import('../src/config/templates.ts');

const agent = (name: string, description?: string, extra: Partial<PresetAgent> = {}): PresetAgent => ({ name, model: null, effort: null, ...(description !== undefined ? { description } : {}), ...extra });
const preset = (agents: PresetAgent[] = [], advisor: string | null = null): Preset => ({
  version: 1,
  main: { model: null, effort: null, autoCompactWindow: null },
  advisor: { model: advisor },
  agents,
  allowBuiltins: true,
  updatedAt: null,
});

test('内置类型清单和后端的一致', () => {
  assert.deepEqual(BUILTIN_AGENT_NAMES, BUILTIN_AGENT_TYPES);
});

test('没有子 agent 也没有 advisor：空字符串；只有 advisor：就是早先的三条', () => {
  assert.equal(defaultRuleText(preset()), '');
  assert.equal(ruleSummary(preset()), '');
  assert.equal(defaultRuleText(preset([], 'fable')), ADVISOR_RULE_TEXT);
  assert.equal(ruleSummary(preset([], 'fable')), 'advisor 3 条');
  assert.match(ADVISOR_RULE_TEXT, /^## 何时咨询 advisor\n\n- 动手做一个大的计划之前/);
});

test('有子 agent：分工一段列出每个子 agent 和通用规则；没有 advisor 就没有 advisor 一段', () => {
  const t = defaultRuleText(preset([agent('explorer', '读代码时使用。'), agent('worker', '改代码时使用。')]));
  assert.ok(t.startsWith(`${DIVISION_HEADING}\n`));
  assert.ok(t.includes('- `explorer`：读代码时使用。\n- `worker`：改代码时使用。'));
  assert.match(t, /负责理解需求、拆分任务、验收结果和向用户汇报/);
  assert.match(t, /不要自己写大段代码/);
  assert.match(t, /互不依赖的任务同时派发/);
  assert.match(t, /一两行的小改动可以自己直接做/);
  assert.match(t, /子 agent 看不到你和用户的对话/);
  assert.match(t, /如果你是被派发出来的子 agent，忽略这一节/);
  assert.doesNotMatch(t, /advisor/);
  assert.equal(ruleSummary(preset([agent('explorer', 'x'), agent('worker', 'y')])), '分工 2 个子 agent');
  // 两段都有：分工在前，advisor 在后，中间空一行
  const both = defaultRuleText(preset([agent('explorer', '读代码时使用。')], 'fable'));
  assert.ok(both.endsWith(`\n\n${ADVISOR_RULE_TEXT}`));
  assert.equal(ruleSummary(preset([agent('a', 'x'), agent('b', 'y'), agent('c', 'z')], 'fable')), '分工 3 个子 agent · advisor 3 条');
});

test('内置类型不列（不区分大小写）；只有内置类型时没有分工一段；没有描述时只列名字，旧方案的 note 当描述', () => {
  const t = defaultRuleText(preset([agent('Explore'), agent('general-purpose', '通用'), agent('plan'), agent('reviewer', undefined, { note: '审查' }), agent('bare')]));
  assert.doesNotMatch(t, /Explore|general-purpose|`plan`/);
  assert.ok(t.includes('- `reviewer`：审查\n- `bare`\n'));
  assert.equal(defaultRuleText(preset([agent('Explore'), agent('Plan')])), '');
  assert.deepEqual(ruleOutline(preset([agent('Explore')], 'opus')), { agents: [], advisor: true });
});

test('description：短的整段保留（合并换行和空白）；长的取第一句；第一句还太长就截断', () => {
  assert.equal(ruleWhen('读代码。\n  需要时使用。'), '读代码。 需要时使用。');
  const long = `第一句说清楚它做什么。${'后面还有很多很多补充说明'.repeat(10)}`;
  assert.equal(ruleWhen(long), '第一句说清楚它做什么。');
  assert.equal(ruleWhen(`Use it for code search. ${'More details here. '.repeat(10)}`), 'Use it for code search.');
  const noStop = '没有句号'.repeat(40);
  const w = ruleWhen(noStop);
  assert.equal(w.length, 90);
  assert.ok(w.endsWith('…'));
  assert.equal(ruleWhen(undefined), '');
  // 模板的描述都不长，整段列出
  for (const n of ['explorer', 'worker', 'researcher']) assert.equal(ruleWhen(agentTemplate(n).description), agentTemplate(n).description);
});

test('项目方案叠加全局方案：项目的在前、全局的在后，同名用项目的（不区分大小写）；advisor 项目没设时用全局的', () => {
  const global = preset([agent('researcher', '查资料时使用。'), agent('Worker', '全局的 worker。')], 'fable');
  const project = preset([agent('worker', '项目的 worker。')]);
  const o = ruleOutline(project, global);
  assert.deepEqual(o.agents, [
    { name: 'worker', when: '项目的 worker。' },
    { name: 'researcher', when: '查资料时使用。' },
  ]);
  assert.equal(o.advisor, true);
  const t = defaultRuleText(project, global);
  assert.doesNotMatch(t, /全局的 worker/);
  assert.match(t, /## 何时咨询 advisor/);
  // 全局规则只列全局方案的 agent
  assert.doesNotMatch(defaultRuleText(global), /项目的 worker/);
  // 空的项目方案 + 空的全局方案
  assert.equal(defaultRuleText(preset(), preset()), '');
});

test('looksAutoGenerated：自动生成的（新旧版本）是，用户自己写的不是', () => {
  const tpl = preset(['explorer', 'worker', 'researcher'].map((n) => agent(n, agentTemplate(n).description)), 'fable');
  assert.equal(looksAutoGenerated(defaultRuleText(tpl)), true);
  assert.equal(looksAutoGenerated(ADVISOR_RULE_TEXT.replace(/\n/g, '\r\n')), true);
  assert.equal(looksAutoGenerated('## 我的规则\n- 用中文'), false);
  assert.equal(looksAutoGenerated(''), false);
});
