// CLAUDE.md 里 agentree 规则块的默认文字：按方案自动生成。纯函数，前端和后端共用，不读写文件。
//
// 由两段组成，哪段不适用就不出现：
//   ## 怎么分工         方案里有（非内置类型的）子 agent 时出现：主会话负责什么、有哪些子 agent、派发时遵守什么
//   ## 何时咨询 advisor  方案指定了 advisor 模型时出现，就是早先版本的三条
// 两段都不适用时返回空字符串，这时不应该写规则块。
//
// 为什么要写分工：Claude Code 默认由主会话自己判断要不要派发，只加载了子 agent、不告诉它要分工的话，
// 主会话往往从头到尾自己干。
//
// 项目方案的规则写在项目的 CLAUDE.md 里，列的是项目里实际能用的子 agent：项目方案叠加全局方案
// （和 server/src/conformance.ts 的 overlayPreset 同样的规则：同名用项目的，名字不区分大小写）。
// 换行统一用 \n，后端写文件时按文件原有的换行风格转换。
import type { Preset } from './types.js';

/** Claude Code 的内置 agent 类型，没有定义文件，规则里不列。和 server/src/config.ts 的 BUILTIN_AGENT_TYPES 保持一致（有测试核对） */
export const BUILTIN_AGENT_NAMES = ['general-purpose', 'Explore', 'Plan', 'claude-code-guide', 'statusline-setup', 'claude', 'output-style-setup'];

export const DIVISION_HEADING = '## 怎么分工';
export const ADVISOR_HEADING = '## 何时咨询 advisor';

export const ADVISOR_RULE_LINES = [
  '动手做一个大的计划之前，先问 advisor 这个方向对不对',
  '同一个错误第二次出现时，问 advisor 是不是走错了路',
  '宣布一个耗时长的任务完成之前，问 advisor 有没有遗漏',
];

/** 只有 advisor 那一段时的文字，也是早先版本唯一的默认文字 */
export const ADVISOR_RULE_TEXT = [ADVISOR_HEADING, '', ...ADVISOR_RULE_LINES.map((l) => `- ${l}`)].join('\n');

/** 派发时的通用规则 */
export const DIVISION_RULE_LINES = [
  '要新建或修改文件、写代码、跑测试时，把要求写清楚交给合适的子 agent，不要自己写大段代码',
  '要读懂现有代码或查资料时，交给对应的子 agent，不要自己大范围地翻代码、搜资料',
  '互不依赖的任务同时派发：在同一条回复里发起多个 Agent 调用',
  '一两行的小改动可以自己直接做；上面没有合适的子 agent 时也自己做',
  '子 agent 看不到你和用户的对话：任务说明里要写清背景、要做什么、涉及哪些文件和验收标准',
  '子 agent 交回结果后，先核对是否达到验收标准，再向用户汇报',
];

/** description 超过这么多字时只取第一句 */
const WHEN_MAX = 90;

const isBuiltinName = (name: string) => BUILTIN_AGENT_NAMES.some((b) => b.toLowerCase() === name.trim().toLowerCase());

/** 规则里一个子 agent 的"什么时候用它"：合并空白；太长时取第一句，第一句还太长就截断 */
export function ruleWhen(description: string | null | undefined): string {
  const t = (description ?? '').replace(/\s+/g, ' ').trim();
  if (t.length <= WHEN_MAX) return t;
  const m = /[。！？!?；;]|\.(?=\s)/.exec(t);
  const first = m ? t.slice(0, m.index + 1).trim() : t;
  return first.length <= WHEN_MAX ? first : `${first.slice(0, WHEN_MAX - 1)}…`;
}

export interface RuleOutline {
  /** 分工一段要列的子 agent（不含内置类型），项目方案在前、全局方案在后 */
  agents: Array<{ name: string; when: string }>;
  /** 是否有 advisor 一段 */
  advisor: boolean;
}

/**
 * 规则由哪些内容组成。global 只在项目方案时给：项目方案叠加全局方案之后的子 agent 和 advisor；全局方案传 null
 */
export function ruleOutline(preset: Preset, global: Preset | null = null): RuleOutline {
  const own = preset.agents ?? [];
  const ownNames = new Set(own.map((a) => a.name.trim().toLowerCase()));
  const inherited = (global?.agents ?? []).filter((a) => !ownNames.has(a.name.trim().toLowerCase()));
  const seen = new Set<string>();
  const agents: RuleOutline['agents'] = [];
  for (const a of [...own, ...inherited]) {
    const name = a.name.trim();
    const key = name.toLowerCase();
    if (!name || isBuiltinName(name) || seen.has(key)) continue;
    seen.add(key);
    agents.push({ name, when: ruleWhen(a.description ?? a.note) });
  }
  const advisor = !!(preset.advisor?.model ?? global?.advisor?.model);
  return { agents, advisor };
}

/**
 * 按方案生成规则块的默认文字（不含 agentree 的标记）。两段都不适用时返回空字符串，调用方不应写规则块。
 * global 见 ruleOutline
 */
export function defaultRuleText(preset: Preset, global: Preset | null = null): string {
  const o = ruleOutline(preset, global);
  const parts: string[] = [];
  if (o.agents.length) {
    parts.push(
      [
        DIVISION_HEADING,
        '',
        '这一节只对主会话。如果你是被派发出来的子 agent，忽略这一节，直接完成交给你的任务。',
        '',
        '你（主会话）负责理解需求、拆分任务、验收结果和向用户汇报。具体的活用 Agent 工具交给下面的子 agent：',
        '',
        ...o.agents.map((a) => (a.when ? `- \`${a.name}\`：${a.when}` : `- \`${a.name}\``)),
        '',
        '派发时遵守：',
        '',
        ...DIVISION_RULE_LINES.map((l) => `- ${l}`),
      ].join('\n'),
    );
  }
  if (o.advisor) parts.push(ADVISOR_RULE_TEXT);
  return parts.join('\n\n');
}

/** 规则节点卡片上的一句话，如"分工 3 个子 agent · advisor 3 条"；两段都没有时为空字符串 */
export function ruleSummary(preset: Preset, global: Preset | null = null): string {
  const o = ruleOutline(preset, global);
  const out: string[] = [];
  if (o.agents.length) out.push(`分工 ${o.agents.length} 个子 agent`);
  if (o.advisor) out.push(`advisor ${ADVISOR_RULE_LINES.length} 条`);
  return out.join(' · ');
}

/**
 * 一段规则文字看起来是不是 agentree 自动生成的（任何版本）：以分工的标题开头，或者就是早先那三条 advisor 规则。
 * 用来区分 CLAUDE.md 里现有的规则块是自动生成的，还是用户自己写的
 */
export function looksAutoGenerated(text: string): boolean {
  const t = text.replace(/\r\n/g, '\n').trim();
  return t.startsWith(DIVISION_HEADING + '\n') || t === ADVISOR_RULE_TEXT;
}
